### ISSUE TITLE
Add \# (# is a number) in the cheatsheet

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#10]
As the title says. Add the backreference in the guide ``/(Bob) went with \1 Mom/``

**Comment by sky10p** [comment]
Your suggestion is appreciated. As the sole developer, my current priority is addressing bugs before implementing new features or minor updates. However, your idea has been added to the backlog and will be addressed as promptly as possible.

Thank you for your understanding and patience.

**Comment by sky10p** [comment]
It will be added in the next deployed version
