### ISSUE TITLE
Feature Request – Add a way to time the regex performance

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#11]
Instead of going to whatever regex website(or using a computer) to test the regex... it would be better to do so on the app since it is more comfortable (android applications perk).
This timing feature of course can't be precise on the first application of the regex on the string so i suggest to improve the feature simulating the application of the regex x-times.
"x" can be fixed by the developer or make the user choose the number. The dev has to set a max value allowed.

**Comment by Palloxin** [comment]
![IMG_20240112_093607](https://github.com/sky10p/regexh-contributions/assets/75091899/7af01eb4-7eb2-4fb0-91e9-1ce4253a549d)
Something like this but on websites It is not precise (range from 100ms to 210ms for the same string and regex and can't do the "average speed")
I am a very very casual regex user that can't program so I don't know how others measure their regex performance. You have to search various methods on google for the easiest one.

**Comment by Palloxin** [comment]
or this website
![IMG_20240112_160100](https://github.com/sky10p/regexh-contributions/assets/75091899/9aaa4027-0acc-4a85-a5ef-f5fa0eab6710)
Give the regex and the string => this will come out.

**Comment by sky10p** [comment]
Thank you for your collaboration. I've added your suggestions to the backlog for consideration in future feature developments. Rest assured, your input will be taken into account.

**Comment by sky10p** [comment]
I am working on this, and it will be included in the 5.0.0 version of RegexH
