### ISSUE TITLE
[Bug] Pasted stylized text are “infectious” in the app

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#12]
https://github.com/sky10p/regexh-contributions/assets/75091899/681f2f07-cdfe-4065-bcfb-e98140b1574d

Pasted stylized text, be it in string or regex text box, will "infect" that box until one resets the application. Infect because u can't remove it in any way once u pasted the stylized text unless u reset the app.
Of course it is not just the color, I even found text alignments.

**Comment by sky10p** [comment]
I apologize for the inconvenience you're experiencing. I have conducted tests on both an emulator and my mobile device, and did not encounter this issue, suggesting it might be specific to certain mobile models like yours. In the meantime, until I resolve this issue, please use the 'clear' option in the menu, located at the top right of the app bar, as this should help. Additionally, could yo provide details about your mobile device, including the model, Android version, screen dimensions, etc... in your issue report?

This information will be valuable in addressing the problem.

Thank you very much for your cooperation.

**Comment by sky10p** [comment]
The issue will be resolved in version 4.8.4. It may take several days for the update to be available on Google Play. Accordingly, I am closing this request.
