### ISSUE TITLE
[Bug] Keyboard wrongly summoned

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#13]
How to reproduce
1. Click on the regex box and type ``aaa``
2. click on the string box and type ``aaa``
3. Click on the regex box;
4. click the Back button of android navigation bar;
5. click on the orange highlight
Right here the keyboard will be wrongly summomed

Video:

https://github.com/sky10p/regexh-contributions/assets/75091899/8b00baa7-23b2-4779-8460-c7f7d4e6eac6

OS: Android 8 Miui 8
Device: huawei p8 lite 2017
App ver: 4.8.4

Details: iirc it happens in the 4.8.0 version

**Comment by sky10p** [comment]
I have added to the backlog to check and fix, thanks.

**Comment by sky10p** [comment]
It will be solved in the next deployed version
