### ISSUE TITLE
Warn icon to distinguish between not-match or just regex error

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#18]
Sometimes i write the regex, put the string and doesnt match. I then realize later that there was just a regex error all along (some errors aren't really errors but the app wants the correct syntax like the not acceoted ``[^]``. 
I would like a little icon that indicates that the regex has an error.
The icon appearance should only be processed 2 seconds after the last input in the regex, so for performance reasons dont trigger it before that.

**Comment by Palloxin** [comment]
This icon should be toggle-abke in the settings. I can see it may not be liked by everybody.

**Comment by sky10p** [comment]
The simplest solution is to change the colour of the edit text in the regex field if it is incorrect. This will be implemented in the next version.

**Comment by sky10p** [comment]
The feature has been implemented, it will be released on version 5.6.0, this may take several days until Google review the update.
