### ISSUE TITLE
[Feature Request] Ability to switch Ascii code format

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#19]
![Screenshot_20240418-205636_1](https://github.com/sky10p/regexh-contributions/assets/75091899/57f2e5fe-a3c2-439c-9877-19265aab03fe)

Personally I don't like the ascii code and prefer the Unicode escape sequence
Ascii code: 65533
Unicode escape sequence: \uFFFD

This request is about either permanently changing to unicode escape values or an option in settings to swotch between the two.

**Comment by sky10p** [comment]
This feature has been implemented and will be available from version 5.6.2. It may take several days for Google to review and approve the changes
