### ISSUE TITLE
[Flaw] Captured groups buttons don't place the $n comfortably

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#22]
https://github.com/sky10p/regexh-contributions/assets/75091899/e9809abf-208f-4824-8227-7759a8ea2170

1. When a captured group button is clicked it will add itself ALWAYS on the end of the replacement string.
2. When a captured group button is clicked the text cursor goes automatically at the beginning for no reason.
3. I can't use the text cursor to make the captured group buttons place themself where the cursor is (``1.``)

**Comment by sky10p** [comment]
The correction has been implemented, it will be released on version 5.6.0, this may take several days until Google review the update.
