### ISSUE TITLE
Allow also only strings to be saved, with regex box empty

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#26]
I would like to be able to save only strings in the profiles. I dont want to be forced to input a regex.
![Screenshot_20240422-120905_1_1](https://github.com/sky10p/regexh-contributions/assets/75091899/d1fe2cdb-a82b-45ee-8c6b-c0b010603da0)

### Why
I save very long strings(5k+) to avoid creating them over and over again, and then have them ready for use on whatever regex is fit for it.

If it is so important, maybe add a warn window "Regex is missing, continue anyway?" kinda

**Comment by sky10p** [comment]
I will be released on version 5.6.5
