### ISSUE TITLE
[Aesthetic] Improve “Regex Expression” text style

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#27]
![Screenshot_20240422-121329_1](https://github.com/sky10p/regexh-contributions/assets/75091899/bfa859de-7003-4af4-85a0-f3f30c6a0094)

This is an indicative text, but it looks like real text and not "phantom". I am not sure if i'm clear enough.

Like this:
![Screenshot_20240422-121519_1_1](https://github.com/sky10p/regexh-contributions/assets/75091899/9010865c-1627-4bea-ad83-9c2e4686cd9c)

**Comment by sky10p** [comment]
It's fixed and will be released in version 5.6.3. Google might take several days to review the changes. Sorry for the inconvenience.
