### ISSUE TITLE
[Bug] Split screen makes the app reset the string and regex boxes

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#29]
https://github.com/sky10p/regexh-contributions/assets/75091899/4863ab19-5fc5-46af-ac22-bd6597e363ed

OS: A8 miui 8
Device: huawei p8 lite 2017
app version: 5.6.5

**Comment by sky10p** [comment]
This will be fixed in version 5.8.4. It may take some time to be deployed as it is currently under review by Google.
