### ISSUE TITLE
[Aesthetic flaw] Purple indicator of empty string match is not evenly thick

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#31]
If the empty match is on the extreme left border, the purple indicator will be thinner.
![Screenshot_20240806-123044_1](https://github.com/user-attachments/assets/8940618d-24ce-4465-8b50-0867ce80491d)

I know it's a bug, but frankly speaking I prefer the thinner version to be used everywhere as default. It's more good looking.

**Comment by sky10p** [comment]
This will be fixed in version 5.8.4. It may take some time to be deployed as it is currently under review by Google.
