### ISSUE TITLE
[Bug] Infinite loading with certain patterns

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#33]
string: ``aaa``
regex: ``/$/``

Infinite loading when I use $.

https://github.com/user-attachments/assets/d669f26f-dfdf-49b5-b35c-9c94b202660d

**Comment by Palloxin** [comment]
I found another example without $
string: ``ffffff``
regex: ``/(?<=ff)/``

**Comment by sky10p** [comment]
It has been fixed and will be released in version 5.8.6, please be patient while Google checks the version that has been deployed.
