### ISSUE TITLE
i want to translate the app to chinese,but i cant pull request,can you provide another way to help translate,thanks

### ISSUE THREAD

**Issue by vicentory** [sky10p/regexh-contributions#35]
i want to translate the app to chinese,but i cant pull request,can you provide another way to help translate,thanks.
the app is useful,maybe i am not good at github work.
我可以帮忙翻译这个APP变为中文，但是我不太擅长操作github，没有办法创建分支帮忙翻译。
有其它方式可以帮忙翻译吗？

**Comment by vicentory** [comment]
I have search and pull a requeset,please approve ,thanks .
if have problem, i will change. hope can update google play version.

**Comment by sky10p** [comment]
Hi, I will review your messages and PRs from November onwards due to my unavailability. Thank you for your understanding.

**Comment by sky10p** [comment]
Simplified Chinese will be implemented in the upcoming version **6.0.2**. Please allow a few days for Google to review and approve the update. Thank you for your collaboration.

**Comment by vicentory** [comment]
thanks ,Google play has approved.
