### ISSUE TITLE
Allow quantifiers in non-capturing groups

### ISSUE THREAD

**Issue by Palloxin** [sky10p/regexh-contributions#8]
```js
/(?<=\d+)Bob/
```
string: ``6Bob``
It doesnt match in the app.

The quantifiers not usable in them is really a big hole in the app.

**Comment by sky10p** [comment]
I apologize for the inconvenience caused by the malfunction of the quantifier. I was unaware when the problem started, but I will try to work on this as soon as possible to find a solution.

Thank you for your feedback.

**Comment by sky10p** [comment]
I was looking into these regular expressions, it seems a limitation in regex in Java:

`java.util.regex.PatternSyntaxException: Look-behind pattern matches must have a bounded maximum length near index 8
(?<=\d+)Bob`

If you use \d{1} inside the look-behind expression it works, but I am trying to find a solution.

**Comment by Palloxin** [comment]
On the website regex101.com there is the same problem.
The lookbehind with quantifiers doesnt works but if i switch to ``ECMAScript (Javascript)`` the quantifiers into look behind are accepted just fine.
![IMG_20240113_151031](https://github.com/sky10p/regexh-contributions/assets/75091899/7156d83c-5485-419c-a9e6-e113f0f8cdff)

**Comment by sky10p** [comment]
Currently, RegexH is fully integrated with Java regex, which presents these limitations. Consequently, finding straightforward solutions appears challenging.

I am contemplating two potential approaches, although both require substantial refactoring:

1. Implement a feature in RegexH that detects Java regex pattern errors and prompts the user to modify their regular expression accordingly.
2. Revise the entire codebase to support a stable dependency that can handle regex in Android, such as ECMA Javascript. However, a reliable option has not yet been identified.

I will persist in exploring these solutions, but please be aware that hits process is expected to be time-consuming.

**Comment by sky10p** [comment]
For now, the solution will be shown in the explain section java errors, since this error is solved by limiting the range, for example instead of (<?\+d), you can use (<?\d{1,8}), it will be not considered a specific bug of my app, but I have aggregated the errors in the explain to make it more clear to the user.

It will be added in version 5.0.2, it should be ready for the next week.

**Comment by Palloxin** [comment]
What about ``(a)(?<=\1)``?
